name: iot-jenkins

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "9000:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    user: "1001"
    environment:
      PUID: 1001
      PGID: 1001
      JENKINS_SLAVE_AGENT_PORT: 50000
      TZ: America/Sao_Paulo
    networks:
      - iot-jenkins

volumes:
  jenkins_home:
    name: iot-jenkins-home

networks:
  iot-jenkins:
    name: iot-jenkins-network
