name: iot-jenkins

services:
  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      # - /usr/bin/docker:/usr/bin/docker
    user: "root"
    environment:
      JENKINS_OPTS: "--prefix=/jenkins"
      TZ: America/Sao_Paulo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`iot.marlonangeli.com.br`) && PathPrefix(`/jenkins`)"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins.tls=true"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    networks:
      - traefik-network


volumes:
  jenkins_home:
    name: iot-jenkins-home

networks:
  traefik-network:
    external: true
