name: iot-staging

services:
  logi-api:
    container_name: logi-api-staging
    build:
      context: logi-api/
      dockerfile: Dockerfile
      args:
        COMMIT_HASH: ${COMMIT_HASH}
        NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: staging
    ports:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.logi-api.rule=Host(`iot.marlonangeli.com.br`)"
      - "traefik.http.routers.logi-api.entrypoints=websecure"
      - "traefik.http.routers.logi-api.tls=true"
      - "traefik.http.services.logi-api.loadbalancer.server.port=8080"
    networks:
      - traefik-network
      - default

  postgres:
    container_name: iot-postgres
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default

  # mongodb:
  #   container_name: iot-mongodb
  #   image: mongo:5
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #     MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
  #   volumes:
  #     - mongodb-data:/data/db

  rabbitmq:
    container_name: iot-rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - default

volumes:
  postgres-data:
    name: iot-postgres-data
  mongodb-data:
    name: iot-mongodb-data
  rabbitmq-data:
    name: iot-rabbitmq-data

networks:
  default:
    name: iot-development-network
  traefik-network:
    external: true
