### GET stream events
GET {{API_URL}}/events/stream

### GET events
GET {{API_URL}}/events/consume

### POST event
POST {{API_URL}}/events
Content-Type: application/json

{
    "name": "event1",
    "data": {
        "key1": "value1",
        "key2": "value2"
    }
}

### PATCH close connections
PATCH {{API_URL}}/events/close
